language: rust
sudo: false
cache: cargo
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

stages:
  - test
  - name: deploy
    if: (branch = master AND type IN (push)) OR tag =~ ^v*

script: cargo test

jobs:
  include:
    - stage: deploy
      script: cargo install calcver --bins && cargo login $CARGO_API_KEY && calcver && cargo package --allow-dirty && cargo publish --allow-dirty 
      rust: stable