language: rust
sudo: false
cache: cargo
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

stages:
  - test
  - name: deploy
    if: (branch = master AND type IN (push)) OR tag =~ ^v*

before_install:
  - set -e
  - sudo apt-get update
  - cargo install calcver --bins

script: cargo test

jobs:
  include:
    - stage: deploy
      script: cargo login $CARGO_API_KEY && calcver && cargo package --allow-dirty && cargo publish --allow-dirty 
      rust: stable